spring:
  mail:
    host: smtp.gmail.com         # SMTP 서버
    port: 587                    # TLS 포트
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  application:
    name: shop

  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug

daum:
  postcode:
    api-key: YOUR_DAUM_API_KEY    # 다음 우편번호/지도 API 키
    endpoint: https://postcode.map.daum.net/api/v2/postcode

toss:
  secret-key: YOUR_TOSS_SECRET_KEY
  base-url: https://api.tosspayments.com